const {
  findPending,
  updateArticle,
} = require("./repositories/articleRepository");

async function test() {
  try {
    // Get one pending article
    const articles = await findPending(1);

    if (articles.length === 0) {
      console.log("No pending articles found.");
      return;
    }

    const article = articles[0];

    console.log("Before Update:");
    console.log(article);

    const updated = await updateArticle(article.id, {
      summary: "This is a test summary.",
      content: "This is test content generated by the worker.",
      image_url: "https://example.com/image.jpg",
      author: "Flipper Worker",
      reading_time: 5,
      status: "completed",
    });

    console.log("\nAfter Update:");
    console.log(updated);
  } catch (err) {
    console.error(err);
  }

  process.exit();
}

test();